-- คำสั่งสร้างตารางสำหรับโปรเจกต์ DIB Portal
-- สามารถคัดลอกทั้งหมดนี้ไปวางในเมนู SQL Editor บน Supabase แล้วกด Run ได้ทันที

-- 1. สร้างตาราง พนักงาน (employees)
CREATE TABLE IF NOT EXISTS public.employees (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    nameEn TEXT,
    nickname TEXT,
    dept TEXT,
    pos TEXT,
    status TEXT DEFAULT 'Active',
    avatar TEXT,
    birthday DATE,
    start_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. สร้างตาราง การลา (leave_requests)
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days NUMERIC(4, 1) NOT NULL,
    note TEXT,
    status TEXT DEFAULT 'pending',
    approved_by TEXT,
    request_date DATE DEFAULT CURRENT_DATE,
    ref_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- เปิดสิทธิ์สิทธิ์การอ่านเขียนสำหรับทุกคน (RLS Disabled หรือ Enable Insert/Select)
ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests DISABLE ROW LEVEL SECURITY;
